Random forest clasifer with pipelines and hyperpaameter tuning

In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [2]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [3]:
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [4]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [5]:
df['time'].unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [6]:
df.time

0      Dinner
1      Dinner
2      Dinner
3      Dinner
4      Dinner
        ...
239    Dinner
240    Dinner
241    Dinner
242    Dinner
243    Dinner
Name: time, Length: 244, dtype: category
Categories (2, object): ['Lunch', 'Dinner']

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df['time']=encoder.fit_transform(df['time'])

In [8]:
df.time.unique()

array([0, 1])

In [9]:
## independet and dependable features  
X=df.drop(['tip','time'],axis=1)
y=df['tip']

In [10]:
X.head()

   total_bill     sex smoker  day  size
0       16.99  Female     No  Sun     2
1       10.34    Male     No  Sun     3
2       21.01    Male     No  Sun     3
3       23.68    Male     No  Sun     2
4       24.59  Female     No  Sun     4

In [11]:
y.head()

0    1.01
1    1.66
2    3.50
3    3.31
4    3.61
Name: tip, dtype: float64

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [13]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer  # Hnadle missing values
from sklearn.preprocessing import StandardScaler #feature scaling 
from sklearn.preprocessing  import OneHotEncoder   #Categorical to numerical
from sklearn.compose import ColumnTransformer

In [ ]:
categorical_cols=["sex","smoker","day"],
numericals_cols=["total_bill","size"]

In [15]:
#feature engineering automation
##numeriacal pipelines 
num_pipelines =Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='median')),#missing values handle
        ('scaler', StandardScaler())

    ]
)

##categorical pipelines

cat_pipeline=Pipeline(
    steps=[
         ('imputer',SimpleImputer(strategy='most_frequent')),#missing values handle
         ('onehotencoder', OneHotEncoder(
             
         ))
    ]
)

In [16]:
preprocessor=ColumnTransformer([
    ('num_pipeline',num_pipelines,numericals_cols),
    ('cat_pipeline', cat_pipeline,categorical_cols)
])

In [17]:
print(X_train.columns)

Index(['total_bill', 'sex', 'smoker', 'day', 'size'], dtype='object')

In [18]:
print (list(X_train.columns))

['total_bill', 'sex', 'smoker', 'day', 'size']

In [19]:
from sklearn.ensemble import RandomForestRegressor

In [20]:
from sklearn.metrics import accuracy_score

In [ ]:
from sklearn.pipeline import Pipeline

models = {
    "RF": Pipeline([
        ('preprocessor', preprocessor),
        ('model', RandomForestRegressor())
    ])
}

In [28]:
from sklearn.metrics import r2_score

In [29]:
def evaluate_model(X_train, y_train, X_test, y_test, models):
    report = {}

    for i in range(len(models)):
        model = list(models.values())[i]

        model.fit(X_train, y_train)
        y_test_pred = model.predict(X_test)

        test_model_score = r2_score(y_test, y_test_pred)

        report[list(models.keys())[i]] = test_model_score

    return report

In [30]:
print(evaluate_model(X_train,y_train,X_test,y_test,models))

{'RF': 0.4508819848097567}